
language: java

services:
  - mysql

before_install:
  - mysql -e 'create database if not exists ktorm;'

after_success: 
  - chmod +x auto-upload.sh
  - ./auto-upload.sh

notifications:
  email:
    recipients:
      - me@liuwj.me
    on_success: change
    on_failure: always
